i run this 

import rclpy
from rclpy.node import Node
from std_msgs.msg import String, Float32
import paho.mqtt.client as mqtt

class ROS2MQTTBridge(Node):
    def __init__(self):
        super().__init__('ros2_mqtt_bridge')
          
        
        self.mqtt_client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1)
        self.mqtt_client.connect("192.168.1.39", 1883, 60) ## if i use this pc "localhost" if not replace with IP of the MQTT brocker Pc outside docker is 192.168.1.39
        self.mqtt_client.loop_start()

        self.subscription = self.create_subscription(String, '/detected_status', self.detection_callback, 10)     ### Change topic name  /cmd_vel ....
        self.subscription = self.create_subscription(Float32, 'image/zDepth', self.depth_callback, 10) 
        # self.subscription

    def detection_callback(self, msg):
        # self.get_logger().info('Forwarding: "%s"' % msg.data)
        self.mqtt_client.publish('mqtt_topic', msg.data)


    def depth_callback(self , msg):

        self.mqtt_client.publish("mqtt_topic_zDepth" , str(msg.data))

        

        

def main(args=None):
    rclpy.init(args=args)
    bridge = ROS2MQTTBridge()
    rclpy.spin(bridge)
    bridge.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()

i get this error 

s:/app/augmented-robots/server/nux_ws$ /bin/python3 /app/augmented-robots/server/nux_ws/src/smart_robots_controller/smart_robots_controller/mqtt_bridge.py
/app/augmented-robots/server/nux_ws/src/smart_robots_controller/smart_robots_controller/mqtt_bridge.py:11: DeprecationWarning: Callback API version 1 is deprecated, update to latest version
  self.mqtt_client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1)
Traceback (most recent call last):
  File "/app/augmented-robots/server/nux_ws/src/smart_robots_controller/smart_robots_controller/mqtt_bridge.py", line 40, in <module>
    main()
  File "/app/augmented-robots/server/nux_ws/src/smart_robots_controller/smart_robots_controller/mqtt_bridge.py", line 34, in main
    bridge = ROS2MQTTBridge()
  File "/app/augmented-robots/server/nux_ws/src/smart_robots_controller/smart_robots_controller/mqtt_bridge.py", line 12, in __init__
    self.mqtt_client.connect("192.168.1.39", 1883, 60) ## if i use this pc "localhost" if not replace with IP of the MQTT brocker Pc outside docker is 192.168.1.39
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1429, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1592, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 4598, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 4623, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
